name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.7'
        cabal-version: '3.6'

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build

    - name: Install dependencies
      run: cabal install --only-dependencies --overwrite-policy=always

    - name: Build
      run: cabal build

