name: Release

on:
  push:
    branches: [ 'main' ]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ['9.4.3']
        cabal: ['3.8.1.0']
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest

    name: release-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure environment
        run: |
          git config --global core.autocrlf false

      - uses: actions/checkout@v3

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: deps-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: deps-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Cache
        uses: actions/cache@v2
        with:
          path: dist-newstyle
          key: dist-${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
          restore-keys: dist-${{ runner.os }}-${{ matrix.ghc }}-

      - name: Build
        run: cabal install --install-method=copy --installdir=dist/

      - uses: actions/upload-artifact@v3
        with:
          name: gren-${{ runner.os }}
          path: dist/
          retention-days: 30

