name: Release

on:
  push:
    branches: [ 'main' ]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest

    name: release-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Configure environment
        run: |
          git config --global core.autocrlf false

      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        id: setup-haskell
        with:
          ghc-version: '9.2'
          cabal-version: '3.6'

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-${{ runner.os }}-${{ hashFiles('*.cabal') }}

      - name: Build
        run: cabal install --install-method=copy --installdir=dist/

      - uses: actions/upload-artifact@v3
        with:
          name: gren-${{ runner.os }}
          path: dist/
          retention-days: 30

