name: Release

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    name: Development Build
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '9.2.2'
          cabal-version: '3.6'

      - name: Cache
        uses: actions/cache@v1
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-build

      - name: Build
        run: |
          cabal build
          cp dist-newstyle/build/x86_64-osx/ghc-9.2.2/gren-0.1.0/x/gren/build/gren/gren gren
          strip gren
          zip gren.zip gren

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            gren.zip

