name: Verify build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mrkkrp/ormolu-action@v5

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal
          ~/.ghcup
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal') }}

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '9.2.2'
        cabal-version: '3.6'

    - name: Build
      run: cabal build -f dev

