name: Verify build

on:
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: alpine:3.15
    strategy:
      matrix:
        ghc: ["9.4.2"]
        cabal: ["3.8.1.0"]

    steps:
    - name: Install deps
      run: apk add alpine-sdk autoconf gcc gmp gmp-dev libffi libffi-dev llvm10 make musl-dev ncurses-dev ncurses-static tree wget zlib-dev zlib-static curl

    - uses: actions/checkout@v3

    - name: Install GHCup
      run: curl https://downloads.haskell.org/~ghcup/0.1.18.0/x86_64-linux-ghcup-0.1.18.0 -o /usr/local/bin/ghcup && chmod a+x /usr/local/bin/ghcup

    - name: Cache ghcup
      uses: actions/cache@v2
      with:
        path: $HOME/.ghcup
        key: deps-linux-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: deps-linux-${{ matrix.ghc }}-

    - name: Install Haskell
      run: ghcup install ghc ${{ matrix.ghc }} --set && ghcup install cabal ${{ matrix.cabal }} --set

    - name: Update PATH
      run: echo "$HOME/.ghcup/bin" >> $GITHUB_PATH

    - name: Cabal update
      run: cabal update

    - name: Cache cabal store
      uses: actions/cache@v2
      with:
        path: $HOME/.cabal/store
        key: deps-linux-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: deps-linux-${{ matrix.ghc }}-

    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: dist-newstyle
        key: dist-linux-${{ matrix.ghc }}-${{ github.sha }}
        restore-keys: dist-linux-${{ matrix.ghc }}-

    - name: Build
      run: cabal build --ghc-option=-optl=-static --ghc-option=-split-sections -O2

    - name: Move binary
      run: cp `cabal list-bin .` ./gren_linux

    - name: Strip
      run: strip gren_linux

    - uses: actions/upload-artifact@v3
      with:
        name: gren_linux
        path: gren_linux
        retention-days: 30
