name: Verify build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mrkkrp/ormolu-action@v5

    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '9.2.1'
        cabal-version: '3.6'

    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-build

    - name: Build
      run: cabal build -f dev

