name: Verify build

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: mrkkrp/ormolu-action@v6

    - uses: haskell/actions/setup@v1
      id: setup-haskell
      with:
        ghc-version: '9.4.2'
        cabal-version: '3.8.1.0'

    - name: Cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: deps-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: deps-${{ runner.os }}-${{ matrix.ghc }}-

    - name: Cache
      uses: actions/cache@v2
      with:
        path: dist-newstyle
        key: dist-${{ runner.os }}-${{ matrix.ghc }}-${{ github.sha }}
        restore-keys: dist-${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build
      run: cabal build --enable-tests

    - name: Tests
      run: cabal test
