name: Verify build

on:
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  linux:
    runs-on: ubuntu-latest
    container: alpine:3.15
    strategy:
      matrix:
        ghc: ["9.4.2"]
        cabal: ["3.8.1.0"]

    steps:
    - name: Install deps
      run: apk add --no-cache alpine-sdk autoconf gcc gmp gmp-dev libffi libffi-dev llvm10 make musl-dev ncurses-dev ncurses-static tree wget zlib-dev zlib-static curl

    - uses: actions/checkout@v3


