name: Verify build

on:
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    container: alpine:3.15
    strategy:
      matrix:
        ghc: ["9.4.2"]
        cabal: ["3.8.1.0"]

    steps:
    - name: Install deps
      run: apk add --no-cache alpine-sdk autoconf gcc gmp gmp-dev libffi libffi-dev llvm10 make musl-dev ncurses-dev ncurses-static tree wget zlib-dev zlib-static curl

    - uses: actions/checkout@v3

    - name: Install GHCup
      run: curl https://downloads.haskell.org/~ghcup/0.1.18.0/x86_64-linux-ghcup-0.1.18.0 -o /usr/local/bin/ghcup && chmod a+x /usr/local/bin/ghcup

    - name: Install Haskell
      run: ghcup install ghc #{{ matrix.ghc }} --set && ghcup install cabal ${{ matrix.cabal }} --set
